pipeline {
  agent any
  stages {
    stage('Install dependencies') {
      steps {
        sh "chmod +x install_scripts/install_scripts.sh"
        sh "install_scripts/install_scripts.sh"
      }
    }
    
    stage('Run terraform config files') {
      steps {
        sh "terraform init"
        sh "terraform plan"
        sh "terraform apply -auto-approve"
      }
    }   
  }
}
